# Use root/example as user/password credentials
version: '3.1'

services:

  openelevation:
    build: .
    image: spymovil/open-elevation
    container_name: OpenElevation
    restart: always
    ports:
      - 82:8080     
